name: Rust Setup
description: Install pinned Rust toolchain, cache Cargo artifacts, and print versions
inputs:
  components:
    description: Optional Rust components to install (comma-separated)
    required: false
    default: ''
  targets:
    description: Additional targets to install
    required: false
    default: ''
  install-multilib:
    description: Install gcc-multilib for 32-bit compilation
    required: false
    default: 'false'
  tools: 
    description: Cargo tools to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Cache apt packages
      if: runner.os == 'Linux' && inputs.install-multilib == 'true'
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-gcc-multilib

    - name: Install 32-bit support
      if: runner.os == 'Linux' && inputs.install-multilib == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib

    - name: Install Rust toolchain (from rust-toolchain.toml)
      uses: dtolnay/rust-toolchain@1.85.0
      with:
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - id: cargo-cache
      name: Cache cargo (restore)
      # TODO: remove next line after working again
      #  temporarily work around https://github.com/actions/runner-images/issues/13341
      #  by disabling caching for macOS
      if: runner.os != 'macos'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('rust-toolchain.toml', 'rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache dependency builds
      if: steps.cargo-cache.outputs.cache-hit != 'true' && runner.os != 'macos'
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -f Cargo.lock ]; then
          echo "Cargo.lock is required in CI!" >&2
          exit 1
        fi
        cargo fetch --locked
        cargo test --no-run --release --all --locked

    - name: Clean workspace crates (keep deps)
      shell: bash
      run: |
        set -euo pipefail
        pkgs=$(cargo metadata --no-deps --format-version 1 | python3 -c 'import sys,json; print("\n".join(p["name"] for p in json.load(sys.stdin)["packages"]))')
        for p in $pkgs; do
          cargo clean -p "$p" --release || true
          cargo clean -p "$p" || true
        done

    - name: Install cargo tools 
      if: inputs.tools != ''
      uses: taiki-e/install-action@v2
      with:
        tool: ${{ inputs.tools }}

    - name: Show toolchain
      shell: bash
      run: rustc -Vv && cargo -Vv
